import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LXGW_Marker_Gothic } from "next/font/google";
import "./globals.css";

const lxgw = LXGW_Marker_Gothic ({
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lxgw.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
